### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by VENTO-off** [ChriisH/H1Z1-Server#5]
I have started server, changed IP in config to 127.0.0.1:20042 and started Launcher.exe.

The game starts and it's loading. After a minute it closes and in my browser open a home page of DayBreak.

Here is the output in server console:
```
[LoginServer] Server set up on port 20042
[GatewayServer] Server set up on port 20001


[LoginServer::Info] SessionRequest from {45705CA8}
[LoginServer::Info] session started for {45705CA8}
[LoginServer::Info] SessionReply sent to {45705CA8}
```

Is it possible to fix this?

P.S. The game I have downloaded by typing this: ```download_depot 295110 295111 8395659676467739522```

**Comment by ChriisH** [comment]
It's not actually going to do anything because the player data packets are not done. You can only get this reply and do nothing atm.
