### ISSUE TITLE
Need More Information please not working

### ISSUE THREAD

**Issue by holyschytt** [ChriisH/H1Z1-Server#7]
Doesn't  even work with the version mention to download it just closes the game.. after loading for a minute I tried all i could.. even changed the ports set all of them to my local ip then even tried with just 1 ip and port even changed ip on the second line

It does the same outcome on the updated version

**Comment by Triggl** [comment]
Hi, the project is not finished but only a basis. I think more code needs to be written, but I don't know. I hope that I will get information how far it is and what is still missing. or Whether only the values need to be changed.

**Comment by ChriisH** [comment]
Thanks for letting me know I don't know what I'm talking about :-).

Seriously, the version I mentioned is the correct one, also this project is not actually made to go after the loading screen, it just do the first steps of the official server packet emulation.

**Comment by holyschytt** [comment]
Oh Do you have a discord. ChriisH I like to learn more about this maybe get it past the loading screen.. Really just like to find an Error log or something indicating where it stops at..
